[[redirects]]
  from = "https://pick-the-original.com"
  to = "https://schubert.com"
  status = 301
  force = true

[[redirects]]
  from = "https://pick-the-original.de"
  to = "https://schubert.com"
  status = 301
  force = true
